name: CD
on:
  release:
    types:
      - prereleased
      - released
permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: yarn
      - run: yarn install --immutable
        working-directory: ./packages/evm
      - run: yarn build
        working-directory: ./packages/evm
      - run: ./build-package.sh ./package
        working-directory: ./packages/evm
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: zodiac-modifier-roles-v1-github-workflow
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 sync package/ s3://${{ secrets.S3_BUCKET }}/${{ github.event.release.name }}
        working-directory: ./packages/evm
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: abis
          path: packages/evm/abi/
